### PR TITLE
fixes rust dependency position been on the incorrect line

### PR DESCRIPTION
**Pull request by cjgratacos**
Got some free time on my hand and was able to fix the issue related to this ticket: https://github.com/akinsho/dependency-assist.nvim/issues/3.

### CODE REVIEW

**Comment by cjgratacos** [comment]
closing need to test a couple of things.

**Comment by cjgratacos** [comment]
Reopening it properly passes all my tests ;)

**Comment by cjgratacos** [comment]
@akinsho this PR fixes two issues with rust:

1. dependency highlight moving to the next line.
2. dependency version overwrite caused by dependency containing another dependency name ( aka one dependency contains the substring of another dependency, example serde & serde_json)

**Comment by akinsho** [comment]
@cjgratacos this looks good to me 👍🏿 tested it out locally and seemed to show things on the right lines. Will merge this now then. Thanks for the contribution 🚀

**Pull request merged**
